name: Upload to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'data_pipeline/**'
      - 'model_training/**'
      - 'data_drift/**'

jobs:
  upload_to_gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: coursecompass

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Upload files to GCS
      run: |
        gsutil -m cp -r ./data_pipeline/* gs://mlops-data-7374/
        gsutil -m cp -r ./model_training/* gs://mlops-data-7374/
        gsutil -m cp -r ./data_drift/* gs://mlops-data-7374/
